export enum CustomDataProviderType {
    SEISMIC_SLICES = "SEISMIC_SLICES",
    REALIZATION_GRID_3D = "REALIZATION_GRID_3D",
    REALIZATION_GRID_CELL_FLUX = "REALIZATION_GRID_CELL_FLUX",
    POLYLINES = "POLYLINES",
}
